spring:
  application:
    name: apollo-configservice
  publicId: 182.92.234.157
  datasource:
     url: jdbc:mysql://39.105.162.135/ApolloConfigDB?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
     username: root
     password: TestBicon@123
  cloud:
    inetutils:
      preferredNetworks: ${spring.cloud.client.ipAddress}
    client:
      ipAddress: ${spring.publicId}
      hostname: ${spring.publicId}
ctrip:
  appid: 100003171
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://182.92.234.157:8760/eureka/
  instance:
    ipAddress: ${spring.publicId}
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.publicId}:${server.port}
