server:
  port: 8760
eureka:
  instance:
    hostname: 182.92.234.157
  server:
    #关闭自我保护模式（缺省为打开）
     enable-self-preservation: false
  client:
    #是否将自身注册到eureka
    registerWithEureka: false
    #是否抓取注册信息
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/