spring:
  application:
    name: apollo-configservice
  datasource:
     url: jdbc:mysql://39.105.162.135/ApolloConfigDB?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
     username: root
     password: TestBicon@123
  cloud:
    inetutils:
      preferredNetworks: ${spring.cloud.client.ipAddress}
    client:
      ipAddress: 39.105.162.135
      hostname: ${spring.cloud.client.ipAddress}
ctrip:
  appid: 100003171
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.105.162.135:8760/eureka/
  instance:
    ipAddress: ${spring.cloud.client.ipAddress}
    preferIpAddress: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
